### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by as-if-iam** [kevalpatel2106/PasscodeView#5]
How to set pin size to 4,5,6.
I want to make the size of pin dynamic.
At least three options will help me right now.
Do you have anything for this ?

**Comment by kevalpatel2106** [comment]
You can set the correct PIN in `PinView.setCorrectPin()`. The size of the PIN will be determined based on the length of the correct PIN array.

**Comment by kevalpatel2106** [comment]
@asif84468 PasscodeView now supports dynamic PIN length starting from `v2.0.0`. Check out the [wiki page](https://github.com/kevalpatel2106/PasscodeView/wiki/Static-vs-Dynamic-PIN-indicators) for more detail.
