### ISSUE TITLE
Want override check invalidate auth

### ISSUE THREAD

**Issue by ryansoy** [kevalpatel2106/PasscodeView#9]
i want override invalidate pin number with other process. can u give me example

**Comment by kevalpatel2106** [comment]
@ryansoy What type of the other process you want to authenticate?

**Comment by ryansoy** [comment]
i want override method setCorrectPin(new int[]{1, 2, 3, 4}).
Because when user enter pass completed i will do check with my api service.
Can u help me.

**Comment by kevalpatel2106** [comment]
This library currently doesn't support custom authentication. If you can make appropriate changes and generate PR, I will happily merge it.

**Comment by kevalpatel2106** [comment]
@ryansoy I added the support for custom authentication logic in version `2.0.0`. You can call your API to validate the PIN. Check out [wiki page](https://github.com/kevalpatel2106/PasscodeView/wiki/Custom-authenticator).
